In [1]:
import numpy as np
import scipy as sp
from scipy import sparse
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import IPython
from IPython.display import display
import mglearn
import sys
import sklearn 
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import os
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import GroupKFold
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics.scorer import SCORERS
import warnings
warnings.filterwarnings('ignore')


C:\Users\tbl008\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
C:\Users\tbl008\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
#Wine Quality Data Set - Red
redwine = pd.read_csv("winequality-red.csv", sep=';')

In [3]:
redwine.head(100)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4             0.700         0.00             1.9      0.076   
1             7.8             0.880         0.00             2.6      0.098   
2             7.8             0.760         0.04             2.3      0.092   
3            11.2             0.280         0.56             1.9      0.075   
4             7.4             0.700         0.00             1.9      0.076   
..            ...               ...          ...             ...        ...   
95            4.7             0.600         0.17             2.3      0.058   
96            6.8             0.775         0.00             3.0      0.102   
97            7.0             0.500         0.25             2.0      0.070   
98            7.6             0.900         0.06             2.5      0.079   
99            8.1             0.545         0.18             1.9      0.080   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56   
1                  25.0                  67.0   0.9968  3.20       0.68   
2                  15.0                  54.0   0.9970  3.26       0.65   
3                  17.0                  60.0   0.9980  3.16       0.58   
4                  11.0                  34.0   0.9978  3.51       0.56   
..                  ...                   ...      ...   ...        ...   
95                 17.0                 106.0   0.9932  3.85       0.60   
96                  8.0                  23.0   0.9965  3.45       0.56   
97                  3.0                  22.0   0.9963  3.25       0.63   
98                  5.0                  10.0   0.9967  3.39       0.56   
99                 13.0                  35.0   0.9972  3.30       0.59   

    alcohol  quality  
0       9.4        5  
1       9.8        5  
2       9.8        5  
3       9.8        6  
4       9.4        5  
..      ...      ...  
95     12.9        6  
96     10.7        5  
97      9.2        5  
98      9.8        5  
99      9.0        6  

[100 rows x 12 columns]

In [4]:
display(redwine)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [5]:
print(redwine.shape)

(1599, 12)


In [6]:
#Evaluate supervised model -build model on train set using .fit, evaluate the test set using .score
#Feature selection - quality is the target = y, the data in its entirety = X
array = redwine.values
X = array[:,0:11]
y = array[:,11]

In [7]:
#split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [8]:
#Supervised learning model - Logisitc Regression - fit of train set
logreg = LogisticRegression().fit(X_train, y_train)

In [9]:
#Evaluation of the model using the test set
print("Test set score: {:.2f}".format(logreg.score(X_test, y_test)))

Test set score: 0.62


In [10]:
#Cross-Validation

logreg = LogisticRegression()

In [11]:
#Define X as the data minus the target
X = redwine.drop(columns=['quality'])



In [12]:
X.head

<bound method NDFrame.head of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067  

In [13]:
#Define y as the target - quality
y = redwine['quality'].values

In [14]:
y[0:10]

array([5, 5, 5, 6, 5, 5, 5, 7, 7, 5], dtype=int64)

In [15]:
#Eval of LogReg -default fold cross-val
scores = cross_val_score(logreg, X, y)

In [16]:
print("Cross-validation scores: {}".format(scores))


Cross-validation scores: [0.51962617 0.58161351 0.55743879]


In [17]:
print("Average Cross-validation scores: {:.2f}".format(scores.mean()))

Average Cross-validation scores: 0.55


In [18]:
#Standard K-Fold Cross-val with K (5)
scores = cross_val_score(logreg, X, y, cv=5)

In [19]:
print("Cross-validation scores: {}".format(scores))

Cross-validation scores: [0.54347826 0.52647975 0.60124611 0.59748428 0.59305994]


In [20]:
print("Average cross-validation score: {:.2f}".format(scores.mean()))

Average cross-validation score: 0.57


In [21]:
scores = cross_val_score(logreg, X, y, cv=10)

In [22]:
print("Cross-validation scores: {}".format(scores))

Cross-validation scores: [0.50617284 0.59627329 0.55900621 0.5125     0.53125    0.66875
 0.6125     0.575      0.63291139 0.57324841]


In [23]:
print("Average cross-validation score: {:.2f}".format(scores.mean()))

Average cross-validation score: 0.58


In [24]:
#stratified k-Fold cross-val  #We have to add to this one...will do internet search for syntax
print("Redwine labels:\n{}".format(y))

Redwine labels:
[5 5 5 ... 6 5 6]


In [25]:
#cross val with cross val parameter
kfold = KFold(n_splits=4)

In [26]:
print("Cross-validation scores:\n{}".format(
    cross_val_score(logreg, X, y, cv=kfold)))

Cross-validation scores:
[0.5925     0.56       0.525      0.61654135]


In [27]:
#Do we need this one???
kfold = KFold(n_splits=2)
print("Cross-validation scores:\n{}".format(
    cross_val_score(logreg, X, y, cv=kfold)))

Cross-validation scores:
[0.57875    0.55694618]


In [28]:
#Do we need this one???
kfold = KFold(n_splits=3, shuffle=True, random_state=0)
print("Cross-validation scores:\n{}".format(
    cross_val_score(logreg, X, y, cv=kfold)))

Cross-validation scores:
[0.61350844 0.56285178 0.55347092]


In [29]:
#Leave-one-out cross-val
loo = LeaveOneOut()
scores = cross_val_score(logreg, X, y, cv=loo)
print("Number of cv iterations: ", len(scores))
print("Mean accuracy: {:.2f}".format(scores.mean()))

Number of cv iterations:  1599
Mean accuracy: 0.58


In [30]:
#Shuffle-split cross-validation
shuffle_split = ShuffleSplit(test_size=.5, train_size=.5, n_splits=10)
scores = cross_val_score(logreg, X, y, cv=shuffle_split)
print("Cross-validation scores:\n{}".format(scores))

Cross-validation scores:
[0.585   0.5725  0.57    0.59    0.57625 0.55    0.58625 0.54875 0.56375
 0.59   ]


In [31]:
print("Mean accuracy: {:.2f}".format(scores.mean()))

Mean accuracy: 0.57


In [32]:
#stratified k-fold validation 
def redwine(X, y, inner_cv, outer_cv, Classifier, parameter_grid):
        outer_score = []
        for training_samples, test_samples in outer_cv.split(X, y):
            best_parms = {}
            best_score = -np.inf
            for parameters in parameter_grid:
                cv_scores = []
                for inner_train, innter_test in inner_cv.split(
                        X[training_samples], y[training_samples]):
                    clf = Classifier(**parameters)
                    clf.fit(X[inner_train], y[inner_train])
                    score = clf.score(X[inner_test], y[inner_test])
                    cv_scores.append(score)
                mean_score = np.mean(cv_scores)
                if mean_score > best_score:
                    best_score = mean_score
                    best_params = parameters
            clf = Classifier(**best_params)
            clf.fit(X[training_samples], y[trainin_samples])
            outer_scores.append(clf.score(X[test_samples], y[test_samples]))
        return np.array(outer_scores)

In [33]:
param_grid = {'C': [0.0001, 0.01, 0.1, 1, 10, 100],
             'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
scores = cross_val_score(GridSearchCV(SVC(), param_grid, cv=5),
                        X, y, cv=5)
print("Cross-validation score: ", scores)
print("Mean cross-validation score: ", scores.mean())

Cross-validation score:  [0.51552795 0.50778816 0.59813084 0.55660377 0.59621451]
Mean cross-validation score:  0.5548530476103478


In [60]:
from sklearn.model_selection import ParameterGrid, StratifiedKFold
skfold = StratifiedKFold(n_splits=5, random_state=None)
model_skfold = LogisticRegression()
results_skfold = cross_val_score(model_skfold, X, y, cv=skfold)
print("Accuracy: %.2f%%" % (results_skfold.mean()*100.0))

Accuracy: 57.23%
